PRODUCT_PROPERTY_OVERRIDES += \
    ro.bootimage.build.tags=ro.build.tags \
    ro.bootimage.build.type=ro.build.type \
    ro.bootimage.build.fingerprint=ro.system.build.fingerprint \
    ro.product.bootimage.brand=ro.product.brand \
    ro.product.bootimage.device=ro.system.board \
    ro.product.bootimage.manufacturer=ro.product.manufacturer \
    ro.product.bootimage.model=ro.product.model \
    ro.product.bootimage.name=ro.system.board
PRODUCT_SYSTEM_PROPERTIES += \
    ro.product.board=ro.system.board \
    ro.product.build.fingerprint=ro.system.build.fingerprint
PRODUCT_VENDOR_PROPERTIES += \
    ro.product.vendor_dlkm.brand=ro.product.brand \
    ro.product.vendor_dlkm.device=ro.system.board \
    ro.product.vendor_dlkm.manufacturer=ro.product.manufacturer \
    ro.product.vendor_dlkm.model=ro.product.model \
    ro.product.vendor_dlkm.name=ro.system.board \
    ro.vendor_dlkm.build.fingerprint=ro.system.build.fingerprint
