PRODUCT_PROPERTY_OVERRIDES += \
    ro.bootimage.build.tags=ro.build.tags \
    ro.bootimage.build.type=ro.build.type \
    ro.bootimage.build.fingerprint=ro.system.build.fingerprint \
    ro.product.bootimage.brand=ro.product.brand \
    ro.product.bootimage.device=ro.system.board \
    ro.product.bootimage.manufacturer=ro.product.manufacturer \
    ro.product.bootimage.model=ro.product.model \
    ro.product.bootimage.name=ro.system.board
PRODUCT_SYSTEM_PROPERTIES += \
    ro.build.flavor=ro.system.board_user \
    ro.build.product=ro.system.board \
    ro.product.board=ro.system.board \
    ro.build.description=ro.system.board-user ro.system.build.version.release ro.system.build.id ro.system.build.version.incremental ro.system.build.tags \
    ro.product.build.fingerprint=ro.system.build.fingerprint \
    ro.build.fingerprint=ro.system.build.fingerprint
PRODUCT_PRODUCT_PROPERTIES += \
    ro.product.product.brand=ro.product.brand \
    ro.product.product.device=ro.system.board \
    ro.product.product.manufacturer=ro.product.manufacturer \
    ro.product.product.model=ro.product.model \
    ro.product.product.name=ro.system.board
PRODUCT_SYSTEM_EXT_PROPERTIES += \
    ro.product.system_ext.brand=ro.product.brand \
    ro.product.system_ext.device=ro.system.board \
    ro.product.system_ext.manufacturer=ro.product.manufacturer \
    ro.product.system_ext.model=ro.product.model \
    ro.product.system_ext.name=ro.system.board \
    ro.system_ext.build.fingerprint=ro.system.build.fingerprint
PRODUCT_VENDOR_PROPERTIES += \
    ro.product.vendor_dlkm.brand=ro.product.brand \
    ro.product.vendor_dlkm.device=ro.system.board \
    ro.product.vendor_dlkm.manufacturer=ro.product.manufacturer \
    ro.product.vendor_dlkm.model=ro.product.model \
    ro.product.vendor_dlkm.name=ro.system.board \
    ro.vendor_dlkm.build.fingerprint=ro.system.build.fingerprint
